# Generated by Django 5.1.5 on 2025-03-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'permissions': [('can_unpublish_product', 'Может снимать продукты с публикации'), ('can_delete_any_product', 'Может удалять любые продукты')], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='product',
            name='publish_status',
            field=models.BooleanField(default=False, verbose_name='Публикация продукта'),
        ),
    ]
